# Generated by Django 5.2.1 on 2025-05-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_formadepagamento_venda_produtovendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='horario',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
